services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TMDB_API_KEY: ${TMDB_API_KEY} 
      DB_USER: homeMovieDb  
      DB_PASSWORD: homeMovieDb
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 60s
      retries: 5

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: homeMovieDb
      POSTGRES_PASSWORD: homeMovieDb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "homeMovieDb"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
