version: '3'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TMDB_API_KEY: INSERT API KEY HERE 
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: homeMovieDb
      POSTGRES_PASSWORD: asdfg-01
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
