spring:
    application:
        name: home-movie-db  
tmdb:
    apiKey: ${TMDB_API_KEY}
    apiUrl: https://api.themoviedb.org/3
---
spring:
    config:
        activate:
            on-profile: test
tmdb:
    apiUrl: http://localhost:${mockServerPort}

---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://localhost:3307/homeMovieDb 
        username: homeMovieDb
        password: asdfg-01
logging:
  level:
    '[org.thro.sqs.homemoviedb.home_movie_db_backend]': debug

---
spring:
    config:
        activate: 
            on-profile: prod
    datasource:
        url: jdbc:postgresql://home-movie-db-db-1:5432/homeMovieDb 
        username: ${DB_USER}
        password: ${DB_PASSWORD}

